#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

activate-monitors
nitrogen --restore &

# #Reset all ternary monitors monitors(i only want 2 screens)
# for m in $(get-monitors -t); do
#     bspc monitor $m -r
# done
#
#
# #Initialize monitors
# if [[ $(get-monitors -s) ]]; then
#     bspc monitor "$(get-monitors -s)" -d cmd_2 net_2 dev_2 comm misc
# fi
#
# bspc monitor "$(get-monitors -p)" -d cmd net dev media virt
#
# if [[ $(get-monitors -s) ]]; then
#     bspc wm -O "$(get-monitors -p)" "$(get-monitors -s)"
# else
#     bspc wm -O "$(get-monitors -p)"
# fi


gap=15

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
#As for now, this suffices
bspc config window_gap $gap;
#bspc config top_padding $(($PANEL_HEIGHT-gap))
bspc config top_padding -$gap
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

bspc config border_width      	10

##Color stuff
bspc config normal_frame_opacity 1
bspc config focused_frame_opacity 0.75
bspc config focused_border_color "#9c8c88"
bspc config normal_border_color "#352731"
bspc config presel_border_color "#352731"
bspc config urgent_border_color "#52170c"

bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config leaf_monocle 	  true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='net' follow=on
bspc rule -a Brave-browser desktop='net_2' follow=on
bspc rule -a Vivaldi-stable desktop='net_2' follow=on
bspc rule -a feh desktop='media' follow=on
bspc rule -a VSCodium desktop='dev_2' follow=on
bspc rule -a Element desktop='comm' follow=on
bspc rule -a Virt-manager desktop='virt' follow=on
bspc rule -a KeePass2 desktop='misc' follow=on
bspc rule -a spotify desktop='media' follow=off

#Makes floating windows have shadow
#~/.config/picom/picom_shadow_flag.sh &
#Launches polybars :>
~/.config/polybar/launch.sh
# Launches email
# mutts
